<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-11-05T20:39:54 IST" name="Suite" finished-at="2021-11-05T20:41:38 IST" duration-ms="104662">
    <groups>
    </groups>
    <test started-at="2021-11-05T20:39:54 IST" name="ChromeTest" finished-at="2021-11-05T20:40:31 IST" duration-ms="37759">
      <class name="TestPackage.LoginTest">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:39:54 IST" name="launchBrowser" finished-at="2021-11-05T20:40:17 IST" duration-ms="23782" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="createPOMobject()[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:18 IST" name="createPOMobject" finished-at="2021-11-05T20:40:18 IST" duration-ms="129" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPOMobject -->
        <test-method is-config="true" signature="loginToApplocation(org.testng.ITestResult)[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:18 IST" name="loginToApplocation" finished-at="2021-11-05T20:40:19 IST" duration-ms="1556" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.verify()[pri:0, instance:TestPackage.LoginTest@1151e434] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplocation -->
        <test-method signature="verify()[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:19 IST" name="verify" finished-at="2021-11-05T20:40:30 IST" duration-ms="10743" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://my.exness.com/pa/] but found [https://my.exness.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://my.exness.com/pa/] but found [https://my.exness.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestPackage.LoginTest.verify(LoginTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:30 IST" name="logoutApplication" finished-at="2021-11-05T20:40:30 IST" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="clearPOMobject()[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:30 IST" name="clearPOMobject" finished-at="2021-11-05T20:40:30 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearPOMobject -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:TestPackage.LoginTest@1151e434]" started-at="2021-11-05T20:40:30 IST" name="closeBrowser" finished-at="2021-11-05T20:40:31 IST" duration-ms="1402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- TestPackage.LoginTest -->
    </test> <!-- ChromeTest -->
    <test started-at="2021-11-05T20:40:32 IST" name="FirefoxTest" finished-at="2021-11-05T20:41:38 IST" duration-ms="66585">
      <class name="TestPackage.LoginTest">
        <test-method is-config="true" signature="launchBrowser(java.lang.String)[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:40:32 IST" name="launchBrowser" finished-at="2021-11-05T20:41:24 IST" duration-ms="51797" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="createPOMobject()[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:24 IST" name="createPOMobject" finished-at="2021-11-05T20:41:24 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createPOMobject -->
        <test-method is-config="true" signature="loginToApplocation(org.testng.ITestResult)[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:24 IST" name="loginToApplocation" finished-at="2021-11-05T20:41:27 IST" duration-ms="3242" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name={null} status=CREATED method=LoginTest.verify()[pri:0, instance:TestPackage.LoginTest@20140db9] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApplocation -->
        <test-method signature="verify()[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:27 IST" name="verify" finished-at="2021-11-05T20:41:33 IST" duration-ms="5887" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://my.exness.com/pa/] but found [https://my.exness.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://my.exness.com/pa/] but found [https://my.exness.com/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestPackage.LoginTest.verify(LoginTest.java:88)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verify -->
        <test-method is-config="true" signature="logoutApplication()[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:33 IST" name="logoutApplication" finished-at="2021-11-05T20:41:33 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutApplication -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:33 IST" name="closeBrowser" finished-at="2021-11-05T20:41:38 IST" duration-ms="5651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="clearPOMobject()[pri:0, instance:TestPackage.LoginTest@20140db9]" started-at="2021-11-05T20:41:33 IST" name="clearPOMobject" finished-at="2021-11-05T20:41:33 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearPOMobject -->
      </class> <!-- TestPackage.LoginTest -->
    </test> <!-- FirefoxTest -->
  </suite> <!-- Suite -->
</testng-results>
